### Variables
@baseUrl = http://localhost:3000

### User Endpoints

### Get all users
GET {{baseUrl}}/user?page=1&limit=10&order=DESC
Content-Type: application/json

### Get user by ID
GET {{baseUrl}}/user/6c1dc484-577e-496f-a262-022aa6dc8e2e
Content-Type: application/json

### Create new user
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe 3",
  "email": "john.doesse@example.com"
}

### Update user
PATCH {{baseUrl}}/user/6c1dc484-577e-496f-a262-022aa6dc8e2e
Content-Type: application/json

{
  "name": "John Doe Updated",
  "email": "john.doe.updated@example.com"
}

### Delete user
DELETE {{baseUrl}}/user/6c1dc484-577e-496f-a262-022aa6dc8e2e
Content-Type: application/json

### Category Endpoints

### Get all categories
GET {{baseUrl}}/category?page=1&limit=10&order=DESC
Content-Type: application/json

### Get category by ID
GET {{baseUrl}}/category/1
Content-Type: application/json

### Create new category
POST {{baseUrl}}/category
Content-Type: application/json

{
  "name": "Categoria"
}

### Update category
PATCH {{baseUrl}}/category/1
Content-Type: application/json  

{
  "name": "Category 1 Updated"
}   

### Delete category
DELETE {{baseUrl}}/category/2
Content-Type: application/json  

### Transaction Endpoints

### Get all transactions
GET {{baseUrl}}/transaction?page=1&limit=10
Content-Type: application/json

### Get transaction by ID
GET {{baseUrl}}/transaction/1
Content-Type: application/json

### Create new transaction
POST {{baseUrl}}/transaction
Content-Type: application/json

{
  "title": "Salary",
  "type": "expense",
  "value": 5000,
  "categoryId": "1",
  "userId": "31172ab1-2ef3-4b97-9542-cba3da9c07d5"
}

### Update transaction
PATCH {{baseUrl}}/transaction/3
Content-Type: application/json

{
  "title": "Updated Salary",
  "value": 5500
}

### Delete transaction
DELETE {{baseUrl}}/transaction/3
Content-Type: application/json

### Get total balance
GET {{baseUrl}}/transaction/total-balance/31172ab1-2ef3-4b97-9542-cba3da9c07d5
Content-Type: application/json

### Goal Endpoints

### Get all goals
GET {{baseUrl}}/goal?page=1&limit=10
Content-Type: application/json

### Get goal by ID
GET {{baseUrl}}/goal/5
Content-Type: application/json

### Create new goal
POST {{baseUrl}}/goal
Content-Type: application/json

{
  "name": "Viajar para São Paulo",
  "goalValue": 100,
  "currentValue": 0,
  "completed": false,
  "userId": "31172ab1-2ef3-4b97-9542-cba3da9c07d5"  
}

### Update goal
PATCH {{baseUrl}}/goal/5
Content-Type: application/json

{
  "currentValue": 50
}

### Delete goal
DELETE {{baseUrl}}/goal/5
Content-Type: application/json
